### ISSUE TITLE
Not testing the return code for malloc, just assuming it works.

### ISSUE THREAD

**Issue by ghetzel** [ghetzel/shmtool#1]
https://github.com/ghetzel/shmtool/blob/master/shm/shm.go#L133

Should be making sure `malloc` _really_ `malloc`'d.  Noticed that while reading this:

https://ozlabs.org/~rusty/index.cgi/tech/2008-04-01.html (#5)

**Comment by egorsmkv** [comment]
Any updates on the issue?
