### ISSUE TITLE
sys/shm.h: No such file or directory

### ISSUE THREAD

**Issue by 0colonel0** [ghetzel/shmtool#3]
# github.com/ghetzel/shmtool/shm
In file included from src\github.com\ghetzel\shmtool\shm\shm.go:16:
./shm.h:5:10: fatal error: sys/shm.h: No such file or directory
 #include <sys/shm.h>
          ^~~~~~~~~~~
compilation terminated.

**Comment by ghetzel** [comment]
Can you please provide me with some details about the system you received this error on?

- Operating system (Linux, macOS, Windows)
- OS distribution and version (e.g. Ubuntu 18.04)
- Golang version

Additionally, any context you can offer for what you are trying to do would be helpful.  This is a _very_ Linux-specific library that only exists to solve a somewhat oddly-shaped problem, so it's possible I might recommend something different to tackle your particular problem.

**Comment by 0colonel0** [comment]
windows,golang 1.10,
what can i do to solve the problem？what i need to do?

**Comment by ghetzel** [comment]
Can you tell me what you're using this library for?

I wrote it specifically to solve a Linux-only problem (working with this X11 extension: https://www.x.org/releases/X11R7.7/doc/xextproto/shm.html).  

It is NOT a generic shared memory library, and the project README is fairly clear on this point.

Perhaps give this package a try: https://github.com/hidez8891/shm

**Comment by 0colonel0** [comment]
Thank for you very much.I wang to use it for solving shared memory problem.Implementation of data synchronization between multiple processes

**Comment by ghetzel** [comment]
No problem, sorry for the confusion.
